<?php

namespace Fkuhlmann\TrollhordeBundle\Repository;

/**
 * HordeAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HordeAppRepository extends \Doctrine\ORM\EntityRepository
{
}
