<?php

namespace Fkuhlmann\TrollhordeBundle\Repository;

/**
 * RedditpostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedditpostRepository extends \Doctrine\ORM\EntityRepository
{
}
